### ISSUE TITLE
can not use anymore in blender3.1

### ISSUE THREAD

**Issue by BUGProtectionAssociation** [a1studmuffin/SpaceshipGenerator#43]
Have trouble?

**Comment by ldo** [comment]
What exactly is the problem?

**Comment by doulos0** [comment]
Error for Blender 3.0

Python: Traceback (most recent call last):
  File "/home/doulos/.config/blender/3.0/scripts/addons/SpaceshipGenerator-master/__init__.py", line 43, in execute
    spaceship_generator.generate_spaceship(
  File "/home/doulos/.config/blender/3.0/scripts/addons/SpaceshipGenerator-master/spaceship_generator.py", line 669, in generate_spaceship
    add_surface_antenna_to_face(bm, face)
  File "/home/doulos/.config/blender/3.0/scripts/addons/SpaceshipGenerator-master/spaceship_generator.py", line 341, in add_surface_antenna_to_face
    result = bmesh.ops.create_cone(bm,
TypeError: create_cone: keyword "diameter1" is invalid for this operator

location: <unknown location>:-1

**Comment by ldo** [comment]
Seems that what was called the “diameter” argument in these BMesh operators was in fact being interpreted as the radius all along, according to [this commit](https://git.blender.org/gitweb/gitweb.cgi/blender.git/commit/9b2b32a3338d873529a9b2c402feae4e9d25afdf). Which is why it has been renamed as of 3.0.

**Comment by sbarre** [comment]
I've got a fork of the addon where I've patched the script to work in Blender 3+ 

You can find it here: https://github.com/sbarre/SpaceshipGenerator/tree/blender-3

It was a very simple fix, just a search/replace operation in one file, so you can also just patch your locally installed version of the addon instead.

I've opened a PR on here to discuss it, although I don't think it should be merged into master yet because it might(?) break in 2.9 or lower.

**Comment by ldo** [comment]
Oddly, this particular item missed being mentioned in the [breaking changes](https://wiki.blender.org/wiki/Reference/Release_Notes/3.0/Python_API) to the Python API ...

**Comment by Agroithien** [comment]
> I've got a fork of the addon where I've patched the script to work in Blender 3+
> 
> You can find it here: https://github.com/sbarre/SpaceshipGenerator/tree/blender-3
> 
> It was a very simple fix, just a search/replace operation in one file, so you can also just patch your locally installed version of the addon instead.
> 
> I've opened a PR on here to discuss it, although I don't think it should be merged into master yet because it might(?) break in 2.9 or lower.

Initially, This is not working for me in blender 3.1.2 but I changed 
num_segments = uniform(3, 6) to num_segments = randint(3, 6) 
on line number 340 inside spaceship_generator.py It was a long shot tho. but it worked like a charm...
thanks me later lol...
