### ISSUE TITLE
Python error when tried to add spaceship

### ISSUE THREAD

**Issue by sujaya-manith** [a1studmuffin/SpaceshipGenerator#45]
Python: Traceback (most recent call last):
  File "C:\Users\Sujaya\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\add_mesh_SpaceshipGenerator\__init__.py", line 43, in execute
    spaceship_generator.generate_spaceship(
  File "C:\Users\Sujaya\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\add_mesh_SpaceshipGenerator\spaceship_generator.py", line 669, in generate_spaceship
    add_surface_antenna_to_face(bm, face)
  File "C:\Users\Sujaya\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\add_mesh_SpaceshipGenerator\spaceship_generator.py", line 341, in add_surface_antenna_to_face
    result = bmesh.ops.create_cone(bm,
TypeError: create_cone: keyword "diameter1" is invalid for this operator

location: <unknown location>:-1

**Comment by cubuzz** [comment]
Try this fix: [https://github.com/sbarre/SpaceshipGenerator/tree/blender-3](https://github.com/sbarre/SpaceshipGenerator/tree/blender-3)
Should hopefully be merged here soon.

**Comment by CO501** [comment]
The linked pyton files do not appear to have been merged yet. The same error persists. What should we do?
