### ISSUE TITLE
TypeError: bpy_struct: item.attr = val: enum "Raw" not found in ('Linear', 'sRGB')

### ISSUE THREAD

**Issue by kenorb** [a1studmuffin/SpaceshipGenerator#48]
```
bpy.ops.object.origin_set(type='ORIGIN_CENTER_OF_MASS', center='MEDIAN')
bpy.ops.mesh.generate_spaceship()
Python: Traceback (most recent call last):
  File "/home/kenorb/.config/blender/2.93/scripts/addons/add_mesh_SpaceshipGenerator/__init__.py", line 43, in execute
    spaceship_generator.generate_spaceship(
  File "/home/kenorb/.config/blender/2.93/scripts/addons/add_mesh_SpaceshipGenerator/spaceship_generator.py", line 724, in generate_spaceship
    materials = create_materials()
  File "/home/kenorb/.config/blender/2.93/scripts/addons/add_mesh_SpaceshipGenerator/spaceship_generator.py", line 458, in create_materials
    set_hull_mat_basics(mat, hull_base_color, hull_normal_map)
  File "/home/kenorb/.config/blender/2.93/scripts/addons/add_mesh_SpaceshipGenerator/spaceship_generator.py", line 436, in set_hull_mat_basics
    return add_hull_normal_map(mat, hull_normal_map)
  File "/home/kenorb/.config/blender/2.93/scripts/addons/add_mesh_SpaceshipGenerator/spaceship_generator.py", line 419, in add_hull_normal_map
    teximage_node.image.colorspace_settings.name = 'Raw'
TypeError: bpy_struct: item.attr = val: enum "Raw" not found in ('Linear', 'sRGB')

location: <unknown location>:-1
```

- Blender v2.93.3 on Ubuntu.

**Comment by ldo** [comment]
I would say there is something wrong with your Blender installation -- it is missing a functioning OpenColorIO setup. Because “Raw” is [supposed to be a valid value](https://docs.blender.org/api/master/bpy.types.ColorManagedInputColorspaceSettings.html#bpy.types.ColorManagedInputColorspaceSettings.name) for that field.

Having said that, [my version](https://github.com/ldo/blender_spaceship_generator/blob/01419d97cb691556b001c723a04639a3c96a5353/spaceship_generator.py#L37) only uses “Non-Color” or “sRGB”.
