### ISSUE TITLE
Spaceship generator not working in Blender 3.1

### ISSUE THREAD

**Issue by wulfalpha** [a1studmuffin/SpaceshipGenerator#50]
The error I am getting is this:

```
Python: Traceback (most recent call last):
  File "/home/wulfalpha/.config/blender/3.1/scripts/addons/add_mesh_SpaceshipGenerator/__init__.py", line 43, in execute
    spaceship_generator.generate_spaceship(
  File "/home/wulfalpha/.config/blender/3.1/scripts/addons/add_mesh_SpaceshipGenerator/spaceship_generator.py", line 669, in generate_spaceship
    add_surface_antenna_to_face(bm, face)
  File "/home/wulfalpha/.config/blender/3.1/scripts/addons/add_mesh_SpaceshipGenerator/spaceship_generator.py", line 341, in add_surface_antenna_to_face
    result = bmesh.ops.create_cone(bm,
TypeError: create_cone: keyword "segments" expected an int, not float

location: <unknown location>:-1
```

I have tried a couple of the fixes i have seen here and sadly none of them seems to work. It looks like a type casting issue to me but I can't see where the problem actually is because I'm not familiar enough with python or the code itself. Any help would be great

**Comment by ldo** [comment]
Try [this version](https://github.com/ldo/blender_spaceship_generator).

**Comment by wulfalpha** [comment]
That worked. Thanks!
