### ISSUE TITLE
reports an error when i try to add spaceship

### ISSUE THREAD

**Issue by Enda111** [a1studmuffin/SpaceshipGenerator#51]
<img width="988" alt="Screen Shot 2022-04-13 at 6 45 32 PM" src="https://user-images.githubusercontent.com/30953879/163282560-3ca1c13f-6b73-4172-ac35-81803e322ccb.png">

Report: Error
Python: Traceback (most recent call last):
File "/Users/enda/Library/Application Support/Blender/3.1/scripts/addons/add mesh SpaceshipGenerator/_init_.py",line 43, in execute
spaceship generator.generate spaceship(
File "/Users/enda/Library/Application Support/Blender/3.1/scripts/addons/add mesh SpaceshipGenerator/spaceship generator.py", line 669, in generate spaceship
add surface antenna to face(bm, face)
File "/Users/enda/Library/Application Support/Blender/3.1/scripts/addons/add mesh SpaceshipGenerator/spaceship generator.py", line 341, in add surface antenna to face
result = bmesh.ops.create cone(bm,
TypeError: create cone: keyword "segments" expected an int, not float
location: <unknown location>:-1

**Comment by RetroFromTheEmpire** [comment]
I also have this issue; did you find a solution? :)

**Comment by Phildatlante** [comment]
Same here.

**Comment by don1138** [comment]
To fix this, open **spaceship_generator.py** and change line 340 from:
`num_segments = uniform(3, 6)`
to
`num_segments = randint(3, 6)`

**Comment by Agroithien** [comment]
[](url)> To fix this, open **spaceship_generator.py** and change line 340 from: `num_segments = uniform(3, 6)` to `num_segments = randint(3, 6)`

I  tried this but another error came on please help!!!
![Screenshot (33)](https://user-images.githubusercontent.com/66170717/166405211-f670cac1-5917-49fd-b2e0-68e710c6e6dc.png)
ut...

**Comment by YuzhouGuo** [comment]
> > To fix this, open **spaceship_generator.py** and change line 340 from: `num_segments = uniform(3, 6)` to `num_segments = randint(3, 6)`
> 
> I tried this but another error came on please help!!! ![Screenshot (33)](https://user-images.githubusercontent.com/66170717/166405211-f670cac1-5917-49fd-b2e0-68e710c6e6dc.png) ut...

Hey there, I just came along with the same issue. If you reach out to the latest blender API website you may see that they change the argument namings: https://docs.blender.org/api/current/bmesh.ops.html. I guess the name used to be "diameter" but apparently it is now "radius". So just change all "diameter1" "diameter2" to "radius1" and "radius2" you should be fine.

**Comment by don1138** [comment]
Ah, Yes! Thanks for detailing the solution!

I found that [**ldo** had forked it and got it working](https://github.com/ldo/blender_spaceship_generator), but hadn't yet done a DIFF to see what they had changed.

**Comment by Enda111** [comment]
i also changed so instead of saying diameter1=0, it looks like. dont know if this helps for any bugs or anything :)
<img width="445" alt="Screen Shot 2022-05-04 at 4 28 30 PM" src="https://user-images.githubusercontent.com/30953879/166820594-e142a821-a769-4fa8-b36a-c9e4c586ddff.png">
s

**Comment by don1138** [comment]
It looks like you need to change all instances of `uniform()` to `int()` or `radint()` 

(and make those values whole integers; so no `0.001`, only `1`) 

and all instances of `diameter1` and `diameter2` to `radius1` and  `radius2`.
